# Generated by Django 4.2 on 2024-12-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_respondedmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondedmessage',
            name='message_user',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respondedmessage',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
