# Generated by Django 4.2 on 2024-12-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_respondedmessage_message_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondedmessage',
            name='message_user',
            field=models.TextField(),
        ),
    ]
